name: flutter_demo
description: A new Flutter project.

version: 1.0.0+1                              # 版本和内部版本 格式 “版本”+“内部版本”

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"              # 限制Dart环境版本

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2                     # ios的icon图标
  fluro: ^1.3.7                               # 路由库
  shared_preferences: ^0.4.3                  # 键值对存储
  url_launcher: ^4.0.1                        # url启动，支持电话，短信，网站，邮件
  path_provider: ^0.4.1                       # 获取ios和android常用文件位置，例如app目录
  xml: ^3.2.3                                 # 解析，遍历，查询，转换和构建XML文档
  image_picker: ^0.4.10                       # 图片选择器，或者使用相机拍摄新照片
  cached_network_image: ^0.5.0                # 缓存网络图片
  connectivity: ^0.3.2                        # 获取网络状态
  device_info: ^0.2.1                         # 获取设备信息
  video_player: ^0.7.2                        # 视频播放器
  flutter_svg: ^0.6.3                         # 使用svg
  camera: ^0.2.4                              # 相机组件
  flutter_swiper: ^1.1.4                      # 轮播组件
  flutter_spinkit: ^3.0.0                     # loading组件
  local_auth: ^0.3.0                          # 设备身份验证，比如指纹
  dio: ^1.0.6                                 # http请求库
  font_awesome_flutter: ^8.2.0                # fa的icon库
  fluttertoast: ^2.1.0                        # toast组件
  flutter_redux: ^0.5.2                       # flutter上的redux
  redux: ^3.0.0                               # redux
  redux_thunk: ^0.2.1                         # redux 异步中间件thunk
  redux_persist_flutter: ^0.6.0               # redux持久化
  redux_logging: ^0.3.0                       # 打印当前的redux状态变化

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true                  # 使用 MD 的 icon 和 font

  # 以下是静态资源
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # 以下是适配多种分辨率的写法
  # .../my_icon.png
  # .../2.0x/my_icon.png
  # .../3.0x/my_icon.png

  # 自定义字体
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  